//
//  OnBoardingViewController.swift
//  phincon-attendance-app
//
//  Created by Satriya on 10/03/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

/*
 MARK: This moduls purpose is only for 
 */

import UIKit

class OnBoardingViewController: UIViewController {
    @IBOutlet weak var view2: UIView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        view2.layer.cornerRadius = 21
     
    }
    
    @IBAction func loginPassword(_ sender: Any) {
        dismiss(animated: true, completion: nil)
    }
    
    @IBAction func loginRegister(_ sender: Any) {
        dismiss(animated: true, completion: nil)
    }
}
